language: node_js
services:
  - docker
cache:
  directories:
    - ~/.npm
node_js:
  - '15'
git:
  depth: 3
script:
  - yarn test
  - yarn build
  - docker build . -t=typescript-node-web:travis-build-$TRAVIS_BUILD_NUMBER
on:
  branch: develop 