version: "3.9"

services:
  web:
    build:
      context: .
      dockerfile: develop.Dockerfile
    container_name: typescript-node-web
    volumes: 
      - ".:/app"
    ports:
      - "8082:8081"
    tty: true